#!/bin/sh
import_statement="(import (prefix (only scheme define string-append display)
                      AGIDEL/)
              (only scheme quote)"
for plugin in "$@"; do
import_statement+="(agidel-plugin $plugin)"

done
import_statement+=")"
csi $csi_args -batch -quiet -eval "(begin
        (module agidel_temp (main)
                $import_statement
                (AGIDEL/define (main)
                   (AGIDEL/display (AGIDEL/string-append $(cat /dev/stdin)))))
        (import agidel_temp)
        (main))"
echo
